### ISSUE TITLE
auto filling class  name

### ISSUE THREAD

**Issue by jcc5018** [spatie/laravel-morph-map-generator#14]
First, thanks for this package, its a lot easier than trying to figure it out why my attempt wasnt working out. 

I am not really familiar with how to make pull requests for packages. but I wanted to provide this as a possible improvement instead of throwing an exception could we not just include something like this to automatically generate the class name without having to manually add this to each model? 

  Stick this in the baseModel as you described, and it should create the references automatically from my understanding.  I dont know if there would be a problem with this approach. 

```
public function getMorphClass(): string
    {
        return strtolower(class_basename(static::class));
    }

```

**Comment by jcc5018** [comment]
ok, update with above code..   when working with filament, this creates errors where it can no longer find the class even though the classes are included and referenced in the proper name spaces. 

The filament resource loads with expected information, then pops up an overlay saying    class "model" not found.      use statements are all present in the obvious files. So not sure if filament is loading something else where it is not being referenced?

Ive tried both lowercase and uppercase versions of this.. (removing strtolower)

So when i tried the resolver included in your docs, it removed the errors, but is also putting the fully qualified name in the DB instead of just the model name that I am seeking. 

I am trying to write something that will auto generate the alias's  similar to this:

```
Relation::enforceMorphMap([
    'post' => 'App\Models\Post',
    'video' => 'App\Models\Video',
]);
```

without having to manually write out 100 plus models.  My models are also set up in a module based system,  Module/{mod name}/Models/model.php

I thought this was the purpose of this package, but the resolver doesnt seem to accomplish this goal, and I'm not sure what else to adjust, nor what the filament resource is trying to call. 

```
MorphMapGenerator::resolveUsing(function ($model) {
         return Str::singular($model->getTable());
      });

```
Any guidance would be appreciated. Thanks

**Comment by rubenvanassche** [comment]
We basically generate a morph map you would manually write, so I can't see why this would not work. Sicne you're using class_basename, are you sure you're not having two classes with the same name in different namespaces?

That's the reason why we're never going to generate classnames by method, just write it out in a string for those 100 classes, it is a bit of work but if you do it once and then for every new class you know the names will be stable and never change.

The resolver allows you to use a method, but I wouldn't use it, too dangerous.

Since there's no real package problem I'm going to close this issue.
