### ISSUE TITLE
Providing a default alias generator?

### ISSUE THREAD

**Issue by mabdullahsari** [spatie/laravel-morph-map-generator#3]
Hello, it's me again 🙃

I'd like to have your take on the fact that perhaps it'd be nice if the package provided a trait which generates sensible defaults for the majority of the use cases? Something along the lines of:

```
trait AliasesMorphType
{
    public function getMorphClass(): string
    {
        return (string) Str::of(class_basename(static::class))
            ->snake()
            ->lower();
    }
}
```

This is what I have been doing the whole time and the example in the README fits this. I'd totally understand though if you'd not like to merge such code, that's why I'm creating an issue before submitting a PR.

Thanks again for all of your packages, much appreciated!

**Comment by rubenvanassche** [comment]
Hi @mabdullahsari,

I don't think that's a good idea since we do not want that these `getMorphClass`'s change. Let's say you have a `PostComment` that would with a trait create `post_comment` as a morph class. When we update the name of `PostComment` to `Comment`, then the morph class would be `post`. 

All the entries in our database with `post_comment` now wouldn't have a relation anymore 😞.

I also had this taught when building the package, so we could rapidly build models, but it isn't a good plan.

Thanks for the input though!
