### ISSUE TITLE
Class users not found on spatie/laravel-comments & spatie/laravel-activitylog

### ISSUE THREAD

**Issue by Jam0r85** [spatie/laravel-morph-map-generator#9]
All of my models extend a base model which uses the following class to generate the morph name.

<img width="630" alt="Screenshot 2022-06-22 at 14 59 45" src="https://user-images.githubusercontent.com/18726355/175266683-67c812ae-cd57-462d-aa10-f4a2df5a2d93.png">

This works great.

However one slight issue is that on a couple of your packages (comments and activity) when referencing the commentator or causer I get a 'class users not found'.

I've edited the following in config/morph-map-generator.php and this has solved the issue.

<img width="699" alt="Screenshot 2022-06-23 at 10 28 02" src="https://user-images.githubusercontent.com/18726355/175269575-74c19ff5-e230-4929-b277-0c2137c6deab.png">

I guess this is because Models\User.php extends \Auth\User::class rather than Eloquent\Model::class?

Posting this as not sure if this is expected behaviour or whether this should be added to the morph-map-generator.php be default?

**Comment by rubenvanassche** [comment]
I think the problem is not these classes since Pivot, User and all of the models of our packages eventually extend from `Model`. The package cannot find these models since they probably are not present within the path the package is searching. The easiest solution is to use the default Laravel morph map feature. I've updated the docs on this.
